### PR TITLE
Fix deprecation warnings

### PR DESCRIPTION
**Pull request by philandstuff**
dry-types 0.12.0 [deprecated Types::Array#member and introduced a
replacement Types::Array#of in the same release][1].  Sigh.

This means that for dry-types <0.12, you must use Types::Array#member
because #of doesn't exist, but for dry-types >=0.12, you must use
Types::Array#of because #member emits a noisy deprecation warning.

This commit is a quick fix: it changes the gemspec to require >= 0.12,
and uses #of.

[1]: https://github.com/dry-rb/dry-types/blob/master/CHANGELOG.md#v0120-2017-09-15

### CODE REVIEW

**Comment by philandstuff** [comment]
BTW I haven't actually tested this - I couldn't see any development or hacking docs to indicate how to run the tests

**Comment by philandstuff** [comment]
I don't see anything in my PR that caused the build to fail 😕 the rubocop issues were there already

**Comment by philandstuff** [comment]
I've also just discovered that these deprecation warnings break `aws-assume-role environment` because they go to $stdout

**Comment by randomvariable** [comment]
Remove the Ruby 2.1 test from `.travis.yml` and it should pass

**Comment by philandstuff** [comment]
@randomvariable if we remove it from `.travis.yml` should `.ruby-version` be updated as well?

**Comment by randomvariable** [comment]
Yup, and the README.md. 

We'll bump to 1.0.0 after this I think.

**Comment by philandstuff** [comment]
rubocop fails massively for me locally, i feel like i'm missing some definitions somewhere. pushed an update as discussed anyway.

**Pull request merged**
