### PR TITLE
Fix #41: Set upper limit on dry-types.

### LINKED ISSUE #41: incompatible with dry-types 0.15.0
dry-types 0.15.0 breaks `object` types, Dry::Types::Struct seems to be a substitute.

```
[dry-types] Dry::Types.module is deprecated and will be removed in the next major version
Use Dry.Types() instead. Beware, it exports strict types by default, for old behavior use Dry.Types(default: :nominal). See more options in the changelog

[dry-types] Dry::Types.module is deprecated and will be removed in the next major version
Use Dry.Types() instead. Beware, it exports strict types by default, for old behavior use Dry.Types(default: :nominal). See more options in the changelog

/home/matefarkas/.rvm/gems/ruby-2.3.5/gems/dry-container-0.7.0/lib/dry/container/resolver.rb:22:in `block in call': Nothing registered with the key "object" (Dry::Container::Error)
	from /home/matefarkas/.rvm/gems/ruby-2.3.5/gems/dry-container-0.7.0/lib/dry/container/resolver.rb:21:in `fetch'
	from /home/matefarkas/.rvm/gems/ruby-2.3.5/gems/dry-container-0.7.0/lib/dry/container/resolver.rb:21:in `call'
	from /home/matefarkas/.rvm/gems/ruby-2.3.5/gems/dry-container-0.7.0/lib/dry/container/mixin.rb:115:in `resolve'
	from /home/matefarkas/.rvm/gems/ruby-2.3.5/gems/dry-container-0.7.0/lib/dry/container/mixin.rb:128:in `[]'
	from /home/matefarkas/.rvm/gems/ruby-2.3.5/gems/dry-types-0.15.0/lib/dry/types.rb:77:in `block in []'
	from /home/matefarkas/.rvm/gems/ruby-2.3.5/gems/concurrent-ruby-1.1.5/lib/concurrent/map.rb:193:in `block in fetch_or_store'
	from /home/matefarkas/.rvm/gems/ruby-2.3.5/gems/concurrent-ruby-1.1.5/lib/concurrent/map.rb:172:in `fetch'
	from /home/matefarkas/.rvm/gems/ruby-2.3.5/gems/concurrent-ruby-1.1.5/lib/concurrent/map.rb:192:in `fetch_or_store'
	from /home/matefarkas/.rvm/gems/ruby-2.3.5/gems/dry-types-0.15.0/lib/dry/types.rb:68:in `[]'
	from /home/matefarkas/.rvm/gems/ruby-2.3.5/gems/aws_assume_role-1.2.1-universal-linux/lib/aws_assume_role/profile_configuration.rb:11:in `<class:ProfileConfiguration>'
	from /home/matefarkas/.rvm/gems/ruby-2.3.5/gems/aws_assume_role-1.2.1-universal-linux/lib/aws_assume_role/profile_configuration.rb:6:in `<top (required)>'
	from /home/matefarkas/.rvm/gems/ruby-2.3.5/gems/aws_assume_role-1.2.1-universal-linux/lib/aws_assume_role/store/shared_config_with_keyring.rb:6:in `require_relative'
	from /home/matefarkas/.rvm/gems/ruby-2.3.5/gems/aws_assume_role-1.2.1-universal-linux/lib/aws_assume_role/store/shared_config_with_keyring.rb:6:in `<top (required)>'
	from /home/matefarkas/.rvm/gems/ruby-2.3.5/gems/aws_assume_role-1.2.1-universal-linux/lib/aws_assume_role.rb:3:in `require_relative'
	from /home/matefarkas/.rvm/gems/ruby-2.3.5/gems/aws_assume_role-1.2.1-universal-linux/lib/aws_assume_role.rb:3:in `<top (required)>'
	from /home/matefarkas/.rvm/gems/ruby-2.3.5/gems/aws_assume_role-1.2.1-universal-linux/lib/aws_assume_role/cli/actions/includes.rb:5:in `require_relative'
	from /home/matefarkas/.rvm/gems/ruby-2.3.5/gems/aws_assume_role-1.2.1-universal-linux/lib/aws_assume_role/cli/actions/includes.rb:5:in `<top (required)>'
	from /home/matefarkas/.rvm/gems/ruby-2.3.5/gems/aws_assume_role-1.2.1-universal-linux/lib/aws_assume_role/cli/actions/abstract_action.rb:3:in `require_relative'
	from /home/matefarkas/.rvm/gems/ruby-2.3.5/gems/aws_assume_role-1.2.1-universal-linux/lib/aws_assume_role/cli/actions/abstract_action.rb:3:in `<top (required)>'
	from /home/matefarkas/.rvm/gems/ruby-2.3.5/gems/aws_assume_role-1.2.1-universal-linux/lib/aws_assume_role/cli/actions/configure_profile.rb:3:in `require_relative'
	from /home/matefarkas/.rvm/gems/ruby-2.3.5/gems/aws_assume_role-1.2.1-universal-linux/lib/aws_assume_role/cli/actions/configure_profile.rb:3:in `<top (required)>'
	from /home/matefarkas/.rvm/gems/ruby-2.3.5/gems/aws_assume_role-1.2.1-universal-linux/lib/aws_assume_role/cli/commands/configure.rb:3:in `require_relative'
	from /home/matefarkas/.rvm/gems/ruby-2.3.5/gems/aws_assume_role-1.2.1-universal-linux/lib/aws_assume_role/cli/commands/configure.rb:3:in `<top (required)>'
	from /usr/share/rvm/rubies/ruby-2.3.5/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/share/rvm/rubies/ruby-2.3.5/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/matefarkas/.rvm/gems/ruby-2.3.5/gems/gli-2.18.0/lib/gli/app.rb:324:in `block in load_commands'
	from /home/matefarkas/.rvm/gems/ruby-2.3.5/gems/gli-2.18.0/lib/gli/app.rb:321:in `each'
	from /home/matefarkas/.rvm/gems/ruby-2.3.5/gems/gli-2.18.0/lib/gli/app.rb:321:in `load_commands'
	from /home/matefarkas/.rvm/gems/ruby-2.3.5/gems/gli-2.18.0/lib/gli/app.rb:34:in `commands_from'
	from /home/matefarkas/.rvm/gems/ruby-2.3.5/gems/aws_assume_role-1.2.1-universal-linux/lib/aws_assume_role/cli.rb:16:in `<module:Cli>'
	from /home/matefarkas/.rvm/gems/ruby-2.3.5/gems/aws_assume_role-1.2.1-universal-linux/lib/aws_assume_role/cli.rb:7:in `<top (required)>'
	from /home/matefarkas/.rvm/gems/ruby-2.3.5/gems/aws_assume_role-1.2.1-universal-linux/bin/aws-assume-role:4:in `require_relative'
	from /home/matefarkas/.rvm/gems/ruby-2.3.5/gems/aws_assume_role-1.2.1-universal-linux/bin/aws-assume-role:4:in `<top (required)>'
	from /home/matefarkas/.rvm/gems/ruby-2.3.5/bin/aws-assume-role:23:in `load'
	from /home/matefarkas/.rvm/gems/ruby-2.3.5/bin/aws-assume-role:23:in `<main>'
	from /home/matefarkas/.rvm/gems/ruby-2.3.5/bin/ruby_executable_hooks:24:in `eval'
	from /home/matefarkas/.rvm/gems/ruby-2.3.5/bin/ruby_executable_hooks:24:in `<main>'
```

### PR DESCRIPTION
**Pull request by farkasmate**

### CODE REVIEW

**Comment by MrPrimate** [comment]
Thanks for this PR. We'll merge for now and look at refactoring the code to support the later version of dry-types.

**Comment by farkasmate** [comment]
Thank you for merging the workaround.

I noticed you haven't made a release of the run command fix nor this one. Could you please tag the releases and or push to RubyGems? It would be a great help.

Cheers,
Mate

**Comment by MrPrimate** [comment]
@farkasmate :man_facepalming: on it

**Comment by farkasmate** [comment]
Thank you.

**Pull request merged**
