### PR TITLE
Add support for Yubikeys as a source for MFA

### PR DESCRIPTION
**Pull request by davbo**
Using a Yubikey to provide TOTP code allows aws-assume-role to call AssumeRole
on roles which require MFA without the user needing to open their authenticator
app and entering a code to the command prompt.

This implementation will store the friendly name of the TOTP secret in the
aws-cli configuration for any role which uses MFA.

### CODE REVIEW

**Comment by davbo** [comment]
Couple of things:

1) is this a workflow you'd like `aws-assume-role` to support?
2) that failure at Travis is interesting, clearly I have shared objects that make this work. I'll see about fixing that.

**Comment by randomvariable** [comment]
I think we would like to support it, but we'd need to make the external library support optional.

The steps to get there would be:
* Documentation on the non-Ruby dependencies, for OS X, Ubuntu and Fedora.
* Wrap `require "smartcard"` in a `rescue LoadError` block, and then add an appropriate error message if someone tries to use a yubikey but doesn't have the libraries installed.

**Comment by davbo** [comment]
Sounds good, thanks @randomvariable.

**Comment by davbo** [comment]
Not really sure how to test usage of the yubikey, any thoughts what tests could be added @randomvariable ?

**Comment by randomvariable** [comment]
Not sure. I think it might involve mocking out the method that tries to access the Yubikey.

I might have a play with this branch this evening with my own Yubikey.

**Comment by davbo** [comment]
Great! Let me know how you get on. On OS X I provisioned the TOTP secret using the [Yubikey Authenticator](https://developers.yubico.com/yubioath-desktop/) app.

**Comment by randomvariable** [comment]
Did some manual testing on a Neo. Have made a PR to your branch.

**Comment by davbo** [comment]
Thanks @randomvariable, I was away last week so didn't get around to looking sooner.

**Pull request merged**
